#[allow(clippy::allow_attributes, reason = "needed to scope lint policy for generated code")]
#[allow(
    clippy::allow_attributes_without_reason,
    reason = "generated tonic/prost code emits allow attributes without reasons"
)]
#[allow(clippy::all, reason = "generated by tonic/prost via include_proto!")]
#[allow(clippy::pedantic, reason = "generated by tonic/prost via include_proto!")]
#[allow(clippy::nursery, reason = "generated by tonic/prost via include_proto!")]
#[allow(clippy::cargo, reason = "generated by tonic/prost via include_proto!")]
mod hello_world {
    tonic::include_proto!("hello_world");
}

use hello_world::GreetUserRequest;
use hello_world::hello_world_client::HelloWorldClient;
use log::{debug, info};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();

    let name = "Chuck Bradley".to_string();
    let remote_endpoint = "http://127.0.0.1:1234";

    let mut client = HelloWorldClient::connect(remote_endpoint).await?;
    debug!("created client:\n{client:#?}");

    info!("sending grpc to '{remote_endpoint}' with name '{name}'");
    let request = tonic::Request::new(GreetUserRequest { name });
    debug!("request to send:\n{request:#?}");

    let response = client.greet_user(request).await?;
    debug!("got response from server:\n{response:#?}");

    let response_message = response.into_inner();
    debug!("response message:\n{response_message:#?}");

    info!("{}", response_message.server_reply);

    Ok(())
}
