#[allow(
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::cargo,
    clippy::restriction,
    unused,
    unused_qualifications,
    reason = "generated by tonic/prost via include_proto!"
)]
pub mod hello_world {
    tonic::include_proto!("hello_world");
}
