#[allow(
    clippy::allow_attributes,
    reason = "needed to scope lint policy for generated code"
)]
#[allow(
    clippy::allow_attributes_without_reason,
    reason = "generated tonic/prost code emits allow attributes without reasons"
)]
#[allow(clippy::all, reason = "generated by tonic/prost via include_proto!")]
#[allow(
    clippy::pedantic,
    reason = "generated by tonic/prost via include_proto!"
)]
#[allow(
    clippy::nursery,
    reason = "generated by tonic/prost via include_proto!"
)]
#[allow(clippy::cargo, reason = "generated by tonic/prost via include_proto!")]
#[allow(
    unused_qualifications,
    reason = "generated tonic/prost code uses explicit qualification"
)]
pub mod hello_world {
    tonic::include_proto!("hello_world");
}
